#!/bin/bash

set -e

FRONTEND_HOST=${FRONTEND_HOST:=""}

if [ "$FRONTEND_HOST" == "" ]
then
    ALLOW_ORIGIN=""
else
    ALLOW_ORIGIN="add_header 'Access-Control-Allow-Origin' 'https://${FRONTEND_HOST}';"
fi

export ALLOW_ORIGIN=$ALLOW_ORIGIN
envsubst < /etc/nginx/conf.d/app.conf.template > /etc/nginx/conf.d/default.conf
exec nginx -g 'daemon off;'
